# Generated by Django 3.2.4 on 2021-06-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'rollNo')},
        ),
    ]
