# Generated by Django 3.2.4 on 2021-06-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
